### ISSUE TITLE
对你的项目蛮有兴趣，希望参与

### ISSUE THREAD

**Issue by lexign** [yuu2lee4/library_be#1]
看了你的项目和代码，感觉蛮好的。
下一步还要什么新的功能吗，也想一起参与写写code。

**Comment by yuu2lee4** [comment]
之前有一些计划，不过暂时不会抽时间来做了，如果感兴趣，您可以fork之后自己玩，也欢迎pr回来
比如config的定义有些混乱、数据库模型的定义需要进一步整理、借书的时候邮件提醒管理员，借书时间快到期的时候提醒借书者，每月生成借书报告给管理员看等等、发挥您的想象力吧
